### ISSUE TITLE
點選 "我的回報" 會導致應用程式中止

### ISSUE THREAD

**Issue by kiang** [newmanchen/tainan-1999#12]
剛安裝在紅米 Note 上面測試，還沒新增任何資料時點選 "我的回報" 會造成程式中止

**Comment by newmanchen** [comment]
OK 我明早看看 謝謝回報

**Comment by newmanchen** [comment]
[NPE](https://github.com/newmanchen/tainan-1999/blob/master/tainan311/src/main/java/tn/opendata/tainan311/MyActivity.java#L94)
requestIds might be null
