### ISSUE TITLE
5/11 更新的程式有問題

### ISSUE THREAD

**Issue by kiang** [newmanchen/tainan-1999#15]
![screenshot_2015-05-12-14-03-02](https://cloud.githubusercontent.com/assets/47844/7580971/f3c8d25a-f8af-11e4-8cbe-477a59a58a42.png)

畫面如附圖，無法安裝

**Comment by misgod** [comment]
剛剛測試一下,我這邊安裝沒問題

**Comment by kiang** [comment]
更新成功了，剛剛不知道是什麼狀況
