### ISSUE TITLE
離線回報問題時會造成程式中止

### ISSUE THREAD

**Issue by kiang** [newmanchen/tainan-1999#16]
試著在離線狀態下操作程式，新增回報的操作進行到 "描述問題及送出回報" 時會造成程式直接中止

**Comment by newmanchen** [comment]
謝謝回報

針對整個 app 的 error handling 還在慢慢補強中 包含網路狀況不好 或是 server 沒有回傳資料 等
需要一點時間 :)

另外針對離線狀態的操作 有考慮要做可以先在離線狀態中 保存使用者的資料
等到使用者到有網路的環境下 再讓使用者選擇送出 #11 
列在 to-do 中

**Comment by newmanchen** [comment]
[LocationUtils.java#78](https://github.com/newmanchen/tainan-1999/blob/master/tainan311/src/main/java/tn/opendata/tainan311/utils/LocationUtils.java#L78)
Access potential null pointer. Check null or set a default empty list.
