### ISSUE TITLE
目前上傳的資料都是亂碼

### ISSUE THREAD

**Issue by kiang** [newmanchen/tainan-1999#17]
市府反應收到的資料中文都變成亂碼，也許需要確認送出資料是 UTF-8 ?

**Comment by newmanchen** [comment]
嗯 我有收到相關信件了
正在跟承包單位溝通中

**Comment by newmanchen** [comment]
fix this by https://github.com/newmanchen/tainan-1999/commit/532ad6c31ef011e47e3d8f86f3c198479e54bb28

test result on postdataserver : http://www.posttestserver.com/data/2015/05/12/newman/20.17.101767916029
